In [1]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [3]:
a

array([1, 2, 3])

In [5]:
k=2
m=3

In [7]:
print(a+b)

[5 7 9]


In [9]:
print(b+a)

[5 7 9]


In [11]:
print(np.array_equal(a+b, b+a))

<IPython.core.display.Javascript object>

True


In [13]:
print((a+b)+c)

[12 15 18]


In [15]:
print(a+(b+c))

[12 15 18]


In [25]:
zv=np.zeros_like(a)

<IPython.core.display.Javascript object>

In [27]:
print(a + zv)

[1 2 3]


In [2]:
import numpy as np

# Define a function to calculate all three norms of a vector
def calculate_norms(vector):
    l1_norm = np.sum(np.abs(vector))
    l2_norm = np.sqrt(np.sum(vector**2))
    chebyshev_norm = np.max(np.abs(vector))
    return l1_norm, l2_norm, chebyshev_norm

# Define a function to calculate distances between two vectors
def calculate_distances(vector1, vector2):
    diff_vector = vector1 - vector2
    l1_distance = np.sum(np.abs(diff_vector))
    l2_distance = np.sqrt(np.sum(diff_vector**2))
    chebyshev_distance = np.max(np.abs(diff_vector))
    return l1_distance, l2_distance, chebyshev_distance