In [15]:
import numpy as np

In [1]:
import numpy as np

# Define the vectors u1, u2, u3
u1 = np.array([2, 0, 0])
u2 = np.array([2, 3, 4])
u3 = np.array([4, 5, 5])

# Apply Gram-Schmidt process to get orthonormal vectors v1, v2, v3

# Step 1: Set w1 = u1
w1 = u1

# Step 2: Make v1 a unit vector in the direction of w1
v1 = w1 / np.linalg.norm(w1)

# Step 3: Subtract the projection of u2 onto v1 from u2 to get w2
w2 = u2 - np.dot(u2, v1) * v1

# Step 4: Make v2 a unit vector in the direction of w2
v2 = w2 / np.linalg.norm(w2)

# Step 5: Subtract the projection of u3 onto v1 and v2 from u3 to get w3
w3 = u3 - np.dot(u3, v1) * v1 - np.dot(u3, v2) * v2

# Step 6: Make v3 a unit vector in the direction of w3
v3 = w3 / np.linalg.norm(w3)

# Output the orthonormal vectors
print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [1. 0. 0.]
v2: [0.  0.6 0.8]
v3: [ 0.   0.8 -0.6]


In [3]:
import numpy as np

# Define the vectors u1, u2, u3
u1 = np.array([2, 2, 4])
u2 = np.array([0, 3, 5])
u3 = np.array([0, 4, 5])

# Apply Gram-Schmidt process to get orthonormal vectors v1, v2, v3

# Step 1: Set w1 = u1
w1 = u1

# Step 2: Make v1 a unit vector in the direction of w1
v1 = w1 / np.linalg.norm(w1)

# Step 3: Subtract the projection of u2 onto v1 from u2 to get w2
w2 = u2 - np.dot(u2, v1) * v1

# Step 4: Make v2 a unit vector in the direction of w2
v2 = w2 / np.linalg.norm(w2)

# Step 5: Subtract the projection of u3 onto v1 and v2 from u3 to get w3
w3 = u3 - np.dot(u3, v1) * v1 - np.dot(u3, v2) * v2

# Step 6: Make v3 a unit vector in the direction of w3
v3 = w3 / np.linalg.norm(w3)

# Output the orthonormal vectors
print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [0.40824829 0.40824829 0.81649658]
v2: [-0.89708523  0.34503278  0.27602622]
v3: [ 0.16903085  0.84515425 -0.50709255]


In [7]:
# write a function to create a function for create the array instead of entering manually

In [9]:
import numpy as np

def create_vectors():
    """
    Function to create an array of vectors dynamically based on user input.
    """
    num_vectors = int(input("Enter the number of vectors: "))
    vectors = []
    for i in range(num_vectors):
        vector = input(f"Enter the components of vector {i + 1} separated by spaces: ")
        vectors.append(np.array([float(x) for x in vector.split()]))
    return vectors

# Gram-Schmidt process function
def gram_schmidt(vectors):
    """
    Perform the Gram-Schmidt process to generate orthonormal vectors.
    """
    orthonormal_vectors = []
    for i, u in enumerate(vectors):
        # Start with the current vector
        w = u.copy()
        # Subtract projections onto all previous orthonormal vectors
        for v in orthonormal_vectors:
            w -= np.dot(u, v) * v
        # Normalize to create the orthonormal vector
        v_normalized = w / np.linalg.norm(w)
        orthonormal_vectors.append(v_normalized)
    return orthonormal_vectors

# Main program
if __name__ == "__main__":
    # Create vectors dynamically
    vectors = create_vectors()
    print("\nInput vectors:")
    for i, vec in enumerate(vectors):
        print(f"u{i + 1}: {vec}")
    
    # Perform Gram-Schmidt process
    orthonormal_vectors = gram_schmidt(vectors)
    print("\nOrthonormal vectors:")
    for i, vec in enumerate(orthonormal_vectors):
        print(f"v{i + 1}: {vec}")

Enter the number of vectors:  3
Enter the components of vector 1 separated by spaces:  5 7 8
Enter the components of vector 2 separated by spaces:  3 4 5
Enter the components of vector 3 separated by spaces:  9 8 7



Input vectors:
u1: [5. 7. 8.]
u2: [3. 4. 5.]
u3: [9. 8. 7.]

Orthonormal vectors:
v1: [0.42562827 0.59587957 0.68100522]
v2: [-0.02566635 -0.74432415  0.6673251 ]
v3: [ 0.90453403 -0.30151134 -0.30151134]


In [11]:
import numpy as np

def create_random_vectors(num_vectors, dimension=3, range_min=-10, range_max=10):
    """
    Function to create an array of random vectors.
    
    Parameters:
        num_vectors (int): Number of vectors to generate.
        dimension (int): Dimension of each vector (default is 3).
        range_min (int): Minimum value for random numbers (default is -10).
        range_max (int): Maximum value for random numbers (default is 10).
        
    Returns:
        list: A list of NumPy arrays representing the random vectors.
    """
    vectors = []
    for _ in range(num_vectors):
        vector = np.random.uniform(range_min, range_max, dimension)
        vectors.append(vector)
    return vectors

def gram_schmidt(vectors):
    """
    Perform the Gram-Schmidt process to generate orthonormal vectors.
    
    Parameters:
        vectors (list): List of input vectors (NumPy arrays).
    
    Returns:
        list: A list of orthonormal vectors.
    """
    orthonormal_vectors = []
    for u in vectors:
        # Start with the current vector
        w = u.copy()
        # Subtract projections onto all previous orthonormal vectors
        for v in orthonormal_vectors:
            w -= np.dot(u, v) * v
        # Normalize to create the orthonormal vector
        v_normalized = w / np.linalg.norm(w)
        orthonormal_vectors.append(v_normalized)
    return orthonormal_vectors

# Main program
if __name__ == "__main__":
    # Input: number of vectors to generate
    num_vectors = int(input("Enter the number of random vectors to generate: "))
    dimension = int(input("Enter the dimension of the vectors: "))
    
    # Generate random vectors
    vectors = create_random_vectors(num_vectors, dimension)
    print("\nRandomly generated vectors:")
    for i, vec in enumerate(vectors):
        print(f"u{i + 1}: {vec}")
    
    # Perform Gram-Schmidt process
    orthonormal_vectors = gram_schmidt(vectors)
    print("\nOrthonormal vectors:")
    for i, vec in enumerate(orthonormal_vectors):
        print(f"v{i + 1}: {vec}")

Enter the number of random vectors to generate:  4
Enter the dimension of the vectors:  4



Randomly generated vectors:
u1: [ 4.80972673 -9.39961579  8.28744129 -5.2759655 ]
u2: [-8.67639648  7.64109129 -8.59669708 -1.71753968]
u3: [-0.13240333 -8.43785265 -0.3586551   5.61439086]
u4: [ 5.06310808 -2.0450431  -9.02006336 -8.92580256]

Orthonormal vectors:
v1: [ 0.33349154 -0.65174023  0.57462549 -0.3658191 ]
v2: [-0.58561982 -0.0381399  -0.20247432 -0.7839636 ]
v3: [-0.39821229 -0.74031533 -0.34030401  0.42137082]
v4: [ 0.62230201 -0.16035348 -0.71624219 -0.27207369]


## **Matrix

In [19]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A.shape

(2, 3)

In [23]:
A[0]

array([1, 2, 3])

In [25]:
A[1]

array([4, 5, 6])

In [28]:
A=np.array([[1,2,3], [6,7,8]])

In [30]:
A

array([[1, 2, 3],
       [6, 7, 8]])

In [34]:
AT = np.transpose(A)

In [36]:
AT

array([[1, 6],
       [2, 7],
       [3, 8]])

In [38]:
AT_T=np.array(np.array(A))

In [40]:
AT_T

array([[1, 2, 3],
       [6, 7, 8]])

In [68]:
O = np.zeros((3, 3))
print(O)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [74]:
D=np.diag([1,2,3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [78]:
IM = np.eye(3)
IM

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
A=np.triu(np.array([[1,2,3],[4,5,6],[7,8,9]]))
A

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [86]:
A=np.tril(np.array([[1,2,3],[4,5,6],[7,8,9]]))
A

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [90]:
#symmnetric
def is_symmetric(matrix):
    return np.array_equal(matrix, matrix.T)

matrix=np.array([[1,2,3],[2,4,5],[3,5,6]])
result=is_symmetric(matrix)

print(result)


True


In [92]:
# Define a 3x3 anti-symmetric matrix
A = np.array([
    [0,  2, -3],
    [-2, 0,  4],
    [3, -4,  0]
])

# Check if the matrix is anti-symmetric
is_anti_symmetric = np.all(A.T == -A)

print("Matrix A:")
print(A)
print("\nIs A anti-symmetric?", is_anti_symmetric)

Matrix A:
[[ 0  2 -3]
 [-2  0  4]
 [ 3 -4  0]]

Is A anti-symmetric? True


In [94]:
def create_row_echelon():
    """
    Create a sample row-echelon matrix.
    """
    A = np.array([
        [1, 2, 3, 4],
        [0, 5, 6, 7],
        [0, 0, 8, 9]
    ])
    return A

# Create and print the row-echelon matrix
A = create_row_echelon()
print("Row-Echelon Matrix:")
print(A)

Row-Echelon Matrix:
[[1 2 3 4]
 [0 5 6 7]
 [0 0 8 9]]


In [96]:
# Define two matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Define a scalar c
c = 3

# Test the properties of addition
additive_identity_A = A + np.zeros(A.shape)  # A + 0 = A
additive_identity_B = B + np.zeros(B.shape)  # B + 0 = B

commutativity = np.array_equal(A + B, B + A)  # A + B = B + A
associativity = np.array_equal(A + (B + A), (A + B) + A)  # (A + B) + A = A + (B + A)

# Test the properties of scalar multiplication
multiplicative_identity_A = c * A  # cA

distributive_scalar_sum = np.array_equal(c * (A + B), c * A + c * B)  # c(A + B) = cA + cB
distributive_scalar_diff = np.array_equal(c * (A - B), c * A - c * B)  # c(A - B) = cA - cB
distributive_vector_sum = np.array_equal((c + c) * A, c * A + c * A)  # (c + c)A = cA + cA
associative_scalar_mult = np.array_equal(c * (c * A), (c * c) * A)  # c(cA) = (cc)A

# Print results
print("Additive Identity (A):", additive_identity_A)
print("Additive Identity (B):", additive_identity_B)
print("Commutativity of Addition:", commutativity)
print("Associativity of Addition:", associativity)

print("\nMultiplicative Identity (A):", multiplicative_identity_A)
print("Distributive Property (Scalar Sum):", distributive_scalar_sum)
print("Distributive Property (Scalar Difference):", distributive_scalar_diff)
print("Distributive Property (Vector Sum):", distributive_vector_sum)
print("Associative Property (Scalar Multiplication):", associative_scalar_mult)

Additive Identity (A): [[1. 2.]
 [3. 4.]]
Additive Identity (B): [[5. 6.]
 [7. 8.]]
Commutativity of Addition: True
Associativity of Addition: True

Multiplicative Identity (A): [[ 3  6]
 [ 9 12]]
Distributive Property (Scalar Sum): True
Distributive Property (Scalar Difference): True
Distributive Property (Vector Sum): True
Associative Property (Scalar Multiplication): True


In [118]:
# Matrix Multiplication
A = np.array([[1, 2, 4], [3, 4, 6]])
print("Print number of Coulmns (A):", A.shape[1])
B = np.array([[5, 6], [7, 8], [1,3]])
print("Print number of row of (B):", B.shape[0])

result=np.dot(B, A)
result

Print number of Coulmns (A): 3
Print number of row of (B): 3


array([[23, 34, 56],
       [31, 46, 76],
       [10, 14, 22]])