# NumPy

In [2]:
import numpy as np

# Numpy Array

In [4]:
#define list of diff car companies
arr_str= ["Mercedes", "BMW", "Audi", "Ferrari", "Tesla"]

In [5]:
#defining the list of number of cylinders in car or numerical elements
arr_num =[5,4,6,7,3]

In [6]:
#converting list to numpy array
np_ar_str= np.array(arr_str)
np_ar_num= np.array(arr_num)
print("numpy Array(arr_str): ",np_ar_str)
print("numpy Array(arr_num): ",np_ar_num)

numpy Array(arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
numpy Array(arr_num):  [5 4 6 7 3]


In [7]:
#printing the data type of list
print("Data type of arr_str: ",type(arr_str))
print("Data type of arr_num: ",type(arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>


In [8]:
#printing the data type after conversion of lists to array
print("Data type of np_arr_str: ",type(np_ar_str))
print("Data type of np_arr_num: ",type(np_ar_num))

Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


# Numpy Matrix (Multidimensional Array)

In [10]:
#info of diff number of cylinders  in a car and we want to display them in a matrix 
matrix =np.array([[1,2,3],[4,5,9],[1,8,9]])
print(matrix)

[[1 2 3]
 [4 5 9]
 [1 8 9]]


In [11]:
#printing datatype
print("Data type of matrix: ",type(matrix))

Data type of matrix:  <class 'numpy.ndarray'>


# Numpy Functions

# np.arange() function

In [14]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
arr2 =np.arange(start=0, stop=10)
print(arr2)

# or

arr2 =np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
matrix4=np.arange(10,21)
matrix4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 1) Adding step size of 5 to create array

In [18]:
arr3= np.arange(start=0,stop=20,step=5)
arr3

array([ 0,  5, 10, 15])

# np.linespace() function

In [20]:
matrix2=np.linspace(0,5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

# 1) generate 10 evenly spaced values between 10 and 20

In [22]:
matrix3=np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# np.zeros() function

In [24]:
matrix5= np.zeros([3,5])
matrix5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
matrix6 =np.zeros([3,5], dtype=int)
matrix6

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#  np.ones() function

In [27]:
matrix7 =np.ones([3,5])
matrix7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
matrix8=np.ones([3,5], int)
matrix8

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# np.eye() function

In [30]:
matrix9 =np.eye(5)
matrix9

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
matrix10=np.eye(5,dtype=int)
matrix10

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Accessing the entries of NumPy Array

# 1) generate an array with 10 random value 

In [34]:
rand_arr=np.random.randn(10)
rand_arr

array([-1.42165617, -1.29729123,  0.61881941,  0.61598655, -1.19165971,
       -0.70595141, -0.95619555,  0.05334847,  0.64293168,  0.38084356])

In [35]:
#accessing 7th entery of rand_arr
print(rand_arr[6])

-0.9561955487804417


In [97]:
#Access multiple non _consecutive entries using np.arange
print("index value to access array: ", np.arange(3,10,3))
print(rand_arr[np.arange(3, 10, 3)])

index value to access array:  [3 6 9]
[ 0.61598655 -0.95619555  0.38084356]


In [81]:
#check the value of rand_arr is greater than 0
rand_arr>0

array([False, False,  True,  True, False, False, False,  True,  True,
        True])

In [83]:
#accessing values from rand_arr greater than 0

print("values greater than 0: ", rand_arr[rand_arr >0])

values greater than 0:  [0.61881941 0.61598655 0.05334847 0.64293168 0.38084356]


In [85]:
 #accessing values from  rand-arr less than 0
print("values less than 0: ", rand_arr[rand_arr <0])

values less than 0:  [-1.42165617 -1.29729123 -1.19165971 -0.70595141 -0.95619555]


In [36]:
#access multiple entries at once using
print(rand_arr[4:9])

[-1.19165971 -0.70595141 -0.95619555  0.05334847  0.64293168]


In [37]:
m1= np.arange(10,51,10)
m1

array([10, 20, 30, 40, 50])

In [38]:
print(m1[2:4])

[30 40]


In [39]:
print(m1[2:-2])

[30]


 # Saving and loading into nNumpy Array

In [103]:
#creating a random matrices
rand_m1= np.random.randint(1,10,10).reshape(2,5)
print(rand_m1)
print("")
rand_m2= np.random.randint(10,20,10).reshape(2,5)
print(rand_m1)

[[7 1 5 8 8]
 [9 8 8 1 5]]

[[7 1 5 8 8]
 [9 8 8 1 5]]


# np.save() function

In [118]:
np.save("save_np_file",rand_m1)

# np.savez() function

In [121]:
np.savez("save_np_multiplefile",
         rand_m1 =rand_m2,
        rand_m2=rand_m1
        )

# np.load() function

In [126]:
loaded_arr =np.load("save_np_file.npy")
loaded_multi =np.load("save_np_multiplefile.npz")
print(loaded_arr)
print("")
print(loaded_multi)

[[7 1 5 8 8]
 [9 8 8 1 5]]

NpzFile 'save_np_multiplefile.npz' with keys: rand_m1, rand_m2


In [134]:
print("1st matrix\n: " ,loaded_multi["rand_m1"])
print("2st matrix\n: " ,loaded_multi["rand_m2"])

new_matrix=loaded_multi["rand_m2"]
print("New Matrix:\n",new_matrix)

1st matrix
:  [[11 10 16 13 13]
 [17 15 17 18 19]]
2st matrix
:  [[7 1 5 8 8]
 [9 8 8 1 5]]
New Matrix:
 [[7 1 5 8 8]
 [9 8 8 1 5]]


# np.savetxt() function

In [137]:
np.savetxt("np_text_file.txt", rand_m1,delimiter=",",)

# np.loadtxt() function

In [145]:
np.loadtxt("np_text_file.txt", delimiter=",",)

array([[7., 1., 5., 8., 8.],
       [9., 8., 8., 1., 5.]])

In [153]:
#reshape the loaded matrix
text_arr=np.loadtxt("np_text_file.txt", delimiter=",",)
int_arr =text_arr.astype(int)
reshaped_arr= int_arr.reshape(2,5)
print("array before reshaping: ",int_arr)
print("array after reshaping: ",reshaped_arr)

array before reshaping:  [[7 1 5 8 8]
 [9 8 8 1 5]]
array after reshaping:  [[7 1 5 8 8]
 [9 8 8 1 5]]
